export const routePaths = {
  login: '/login',
  appRoot: '/app',
  dashboard: '/app/dashboard',
  opsUsers: '/app/users/ops',
  shipperUsers: '/app/users/shippers',
  merchantUsers: '/app/users/merchants',
  courierPermissions: '/app/permissions/courier-mobile',
  auditLogs: '/app/audit/logs',
  masterdataHubs: '/app/masterdata/hubs',
  masterdataZones: '/app/masterdata/zones',
  masterdataNdrReasons: '/app/masterdata/ndr-reasons',
  masterdataConfigs: '/app/masterdata/configs',
  dashboardLeaf: 'dashboard',
  opsUsersLeaf: 'users/ops',
  shipperUsersLeaf: 'users/shippers',
  merchantUsersLeaf: 'users/merchants',
  courierPermissionsLeaf: 'permissions/courier-mobile',
  auditLogsLeaf: 'audit/logs',
  masterdataHubsLeaf: 'masterdata/hubs',
  masterdataZonesLeaf: 'masterdata/zones',
  masterdataNdrReasonsLeaf: 'masterdata/ndr-reasons',
  masterdataConfigsLeaf: 'masterdata/configs',
} as const;
