export const queryKeys = {
  dashboard: ['dashboard'],
  shipments: ['shipments'],
  pickups: ['pickups'],
  tasks: ['tasks'],
  manifests: ['manifests'],
  ndr: ['ndr'],
  tracking: ['tracking'],
  masterdataHubs: ['masterdata', 'hubs'],
  masterdataZones: ['masterdata', 'zones'],
  masterdataNdrReasons: ['masterdata', 'ndr-reasons'],
  masterdataConfigs: ['masterdata', 'configs'],
  merchantProfiles: ['masterdata', 'merchant-profiles'],
  courierAreaAssignments: ['masterdata', 'courier-area-assignments'],
  adminUsers: ['admin', 'users'],
  adminAuditLogs: ['admin', 'audit-logs'],
} as const;
