export { masterdataClient } from './masterdata.client';
export {
  useConfigsQuery,
  useCreateConfigMutation,
  useCreateHubMutation,
  useCreateNdrReasonMutation,
  useCreateZoneMutation,
  useHubsQuery,
  useMerchantProfilesQuery,
  useNdrReasonsQuery,
  useRegionalHierarchyQuery,
  useUpdateConfigMutation,
  useUpdateHubMutation,
  useUpdateNdrReasonMutation,
  useUpsertMerchantProfileMutation,
  useUpdateZoneMutation,
  useZonesQuery,
  useCourierAreaAssignmentsQuery,
  useCreateCourierAreaAssignmentMutation,
  useUpdateCourierAreaAssignmentMutation,
  useDeleteCourierAreaAssignmentMutation,
} from './masterdata.hooks';
