export const routePaths = {
  login: '/login',
  appRoot: '/app',
  dashboard: '/app/dashboard',
  shipments: '/app/shipments',
  shipmentDetail: (shipmentId: string) => `/app/shipments/${shipmentId}`,
  pickups: '/app/pickups',
  pickupDetail: (pickupId: string) => `/app/pickups/${pickupId}`,
  tasks: '/app/tasks',
  taskDetail: (taskId: string) => `/app/tasks/${taskId}`,
  manifests: '/app/manifests',
  manifestDetail: (manifestId: string) => `/app/manifests/${manifestId}`,
  scans: '/app/scans',
  ndr: '/app/ndr',
  ndrDetail: (ndrId: string) => `/app/ndr/${ndrId}`,
  tracking: '/app/tracking',
  trackingDetail: (shipmentCode: string) => `/app/tracking/${encodeURIComponent(shipmentCode)}`,
  masterdataHubs: '/app/masterdata/hubs',
  masterdataZones: '/app/masterdata/zones',
  masterdataNdrReasons: '/app/masterdata/ndr-reasons',
  masterdataConfigs: '/app/masterdata/configs',
  dashboardLeaf: 'dashboard',
  shipmentsLeaf: 'shipments',
  shipmentDetailLeaf: 'shipments/:shipmentId',
  pickupsLeaf: 'pickups',
  pickupDetailLeaf: 'pickups/:pickupId',
  tasksLeaf: 'tasks',
  taskDetailLeaf: 'tasks/:taskId',
  manifestsLeaf: 'manifests',
  manifestDetailLeaf: 'manifests/:manifestId',
  scansLeaf: 'scans',
  ndrLeaf: 'ndr',
  ndrDetailLeaf: 'ndr/:ndrId',
  trackingLeaf: 'tracking',
  trackingDetailLeaf: 'tracking/:shipmentCode',
  masterdataHubsLeaf: 'masterdata/hubs',
  masterdataZonesLeaf: 'masterdata/zones',
  masterdataNdrReasonsLeaf: 'masterdata/ndr-reasons',
  masterdataConfigsLeaf: 'masterdata/configs',
} as const;
