export const queryKeys = {
  dashboard: ['dashboard'],
  opsAudit: ['ops-audit'],
  shipments: ['shipments'],
  changeRequests: ['change-requests'],
  pickups: ['pickups'],
  tasks: ['tasks'],
  manifests: ['manifests'],
  ndr: ['ndr'],
  tracking: ['tracking'],
  payments: ['payments'],
  masterdataHubs: ['masterdata', 'hubs'],
  masterdataZones: ['masterdata', 'zones'],
  masterdataNdrReasons: ['masterdata', 'ndr-reasons'],
  masterdataConfigs: ['masterdata', 'configs'],
} as const;
