export const colors = {
  primary: {
    50: '#EEF2FF',
    100: '#E0E7FF',
    200: '#C7D2FE',
    300: '#A5B4FC',
    400: '#818CF8',
    500: '#6366F1',
    600: '#4F46E5',
    700: '#4338CA',
    800: '#3730A3',
    900: '#312E81',
  },
  secondary: {
    50: '#EEF2FF',
    100: '#E0E7FF',
    200: '#C7D2FE',
    300: '#A5B4FC',
    400: '#818CF8',
    500: '#6366F1',
    600: '#4F46E5',
    700: '#4338CA',
    800: '#3730A3',
    900: '#312E81',
  },
  background: {
    default: '#EEF2FF',
    subtle: '#E0E7FF',
    elevated: '#EEF2FF',
  },
  surface: {
    default: '#FFFFFF',
    subtle: '#F5F7FF',
    tint: '#EEF2FF',
  },
  text: {
    primary: '#334155',
    secondary: '#475569',
    muted: '#64748B',
    inverse: '#FFFFFF',
  },
  border: {
    default: '#E2E8F0',
    subtle: '#E2E8F0',
    strong: '#CBD5E1',
    focus: '#4F46E5',
  },
  success: {
    soft: '#DCFCE7',
    default: '#15803D',
    strong: '#166534',
  },
  warning: {
    soft: '#FFEDD5',
    default: '#EA8A2F',
    strong: '#C25B12',
  },
  danger: {
    soft: '#FEE2E2',
    default: '#DC3C3C',
    strong: '#B42323',
  },
  info: {
    soft: '#EEF2FF',
    default: '#4F46E5',
    strong: '#4338CA',
  },
} as const;

export const semanticColors = {
  primary: colors.primary[600],
  primarySoft: colors.primary[700],
  primaryMuted: colors.primary[500],
  secondary: colors.secondary[500],

  background: colors.background.default,
  backgroundSubtle: colors.background.subtle,
  surface: colors.surface.default,
  surfaceSubtle: colors.surface.subtle,
  surfaceTint: colors.surface.tint,

  textPrimary: colors.text.primary,
  textSecondary: colors.text.secondary,
  textMuted: colors.text.muted,
  textInverse: colors.text.inverse,

  border: colors.border.default,
  borderSubtle: colors.border.subtle,
  borderStrong: colors.border.strong,
  borderFocus: colors.border.focus,

  success: colors.success.default,
  successSoft: colors.success.soft,
  warning: colors.warning.default,
  warningSoft: colors.warning.soft,
  danger: colors.danger.default,
  dangerSoft: colors.danger.soft,
  info: colors.info.default,
  infoSoft: colors.info.soft,
} as const;
