export const colors = {
  primary: {
    50: '#EFF6FF',
    100: '#DBEAFE',
    200: '#BFDBFE',
    300: '#93C5FD',
    400: '#60A5FA',
    500: '#3B82F6',
    600: '#1D4ED8',
    700: '#1D4ED8',
    800: '#1D4ED8',
    900: '#1D4ED8',
  },
  secondary: {
    50: '#EFF6FF',
    100: '#DBEAFE',
    200: '#BFDBFE',
    300: '#93C5FD',
    400: '#60A5FA',
    500: '#1D4ED8',
    600: '#1D4ED8',
    700: '#1D4ED8',
    800: '#1D4ED8',
    900: '#1D4ED8',
  },
  background: {
    default: '#F8FBFF',
    subtle: '#EFF6FF',
    elevated: '#F8FBFF',
  },
  surface: {
    default: '#FFFFFF',
    subtle: '#F8FBFF',
    tint: '#EFF6FF',
  },
  text: {
    primary: '#334155',
    secondary: '#475569',
    muted: '#64748B',
    inverse: '#FFFFFF',
  },
  border: {
    default: '#E2E8F0',
    subtle: '#E2E8F0',
    strong: '#CBD5E1',
    focus: '#1D4ED8',
  },
  success: {
    soft: '#DCFCE7',
    default: '#15803D',
    strong: '#166534',
  },
  warning: {
    soft: '#FFEDD5',
    default: '#EA8A2F',
    strong: '#C25B12',
  },
  danger: {
    soft: '#FEE2E2',
    default: '#DC3C3C',
    strong: '#B42323',
  },
  info: {
    soft: '#EFF6FF',
    default: '#1D4ED8',
    strong: '#1D4ED8',
  },
} as const;

export const semanticColors = {
  primary: colors.primary[600],
  primarySoft: colors.primary[700],
  primaryMuted: colors.primary[500],
  secondary: colors.secondary[500],

  background: colors.background.default,
  backgroundSubtle: colors.background.subtle,
  surface: colors.surface.default,
  surfaceSubtle: colors.surface.subtle,
  surfaceTint: colors.surface.tint,

  textPrimary: colors.text.primary,
  textSecondary: colors.text.secondary,
  textMuted: colors.text.muted,
  textInverse: colors.text.inverse,

  border: colors.border.default,
  borderSubtle: colors.border.subtle,
  borderStrong: colors.border.strong,
  borderFocus: colors.border.focus,

  success: colors.success.default,
  successSoft: colors.success.soft,
  warning: colors.warning.default,
  warningSoft: colors.warning.soft,
  danger: colors.danger.default,
  dangerSoft: colors.danger.soft,
  info: colors.info.default,
  infoSoft: colors.info.soft,
} as const;
