export interface FallbackWard {
  code: number;
  name: string;
  wardName?: string;
  district?: string;
  codename: string;
  provinceCode?: number;
}

export interface FallbackProvince {
  code: number;
  name: string;
  codename: string;
  divisionType?: string;
  phoneCode?: number | null;
  wards?: FallbackWard[];
}

export const FALLBACK_VIETNAM_PROVINCES: FallbackProvince[] = [
  {
    code: 79,
    name: 'Thành phố Hồ Chí Minh',
    codename: 'ho_chi_minh',
    divisionType: 'thành phố trung ương',
    wards: [
      { code: 7901, name: 'Phường Bến Nghé (Quận 1)', wardName: 'Phường Bến Nghé', district: 'Quận 1', codename: 'phuong_ben_nghe_quan_1', provinceCode: 79 },
      { code: 7902, name: 'Phường Bến Thành (Quận 1)', wardName: 'Phường Bến Thành', district: 'Quận 1', codename: 'phuong_ben_thanh_quan_1', provinceCode: 79 },
      { code: 7903, name: 'Phường Tân Định (Quận 1)', wardName: 'Phường Tân Định', district: 'Quận 1', codename: 'phuong_tan_dinh_quan_1', provinceCode: 79 },
      { code: 7904, name: 'Phường Phạm Ngũ Lão (Quận 1)', wardName: 'Phường Phạm Ngũ Lão', district: 'Quận 1', codename: 'phuong_pham_ngu_lao_quan_1', provinceCode: 79 },
      { code: 7905, name: 'Phường Võ Thị Sáu (Quận 3)', wardName: 'Phường Võ Thị Sáu', district: 'Quận 3', codename: 'phuong_vo_thi_sau_quan_3', provinceCode: 79 },
      { code: 7906, name: 'Phường 1 (Quận 3)', wardName: 'Phường 1', district: 'Quận 3', codename: 'phuong_1_quan_3', provinceCode: 79 },
      { code: 7907, name: 'Phường 2 (Quận 5)', wardName: 'Phường 2', district: 'Quận 5', codename: 'phuong_2_quan_5', provinceCode: 79 },
      { code: 7908, name: 'Phường 12 (Quận 5)', wardName: 'Phường 12', district: 'Quận 5', codename: 'phuong_12_quan_5', provinceCode: 79 },
      { code: 7909, name: 'Phường Tân Phong (Quận 7)', wardName: 'Phường Tân Phong', district: 'Quận 7', codename: 'phuong_tan_phong_quan_7', provinceCode: 79 },
      { code: 7910, name: 'Phường Tân Thuận Đông (Quận 7)', wardName: 'Phường Tân Thuận Đông', district: 'Quận 7', codename: 'phuong_tan_thuan_dong_quan_7', provinceCode: 79 },
      { code: 7911, name: 'Phường Phú Mỹ (Quận 7)', wardName: 'Phường Phú Mỹ', district: 'Quận 7', codename: 'phuong_phu_my_quan_7', provinceCode: 79 },
      { code: 7912, name: 'Phường Thảo Điền (TP. Thủ Đức)', wardName: 'Phường Thảo Điền', district: 'TP. Thủ Đức', codename: 'phuong_thao_dien_tp_thu_duc', provinceCode: 79 },
      { code: 7913, name: 'Phường An Phú (TP. Thủ Đức)', wardName: 'Phường An Phú', district: 'TP. Thủ Đức', codename: 'phuong_an_phu_tp_thu_duc', provinceCode: 79 },
      { code: 7914, name: 'Phường Linh Trung (TP. Thủ Đức)', wardName: 'Phường Linh Trung', district: 'TP. Thủ Đức', codename: 'phuong_linh_trung_tp_thu_duc', provinceCode: 79 },
      { code: 7915, name: 'Phường Hiệp Phú (TP. Thủ Đức)', wardName: 'Phường Hiệp Phú', district: 'TP. Thủ Đức', codename: 'phuong_hiep_phu_tp_thu_duc', provinceCode: 79 },
      { code: 7916, name: 'Phường 14 (Quận Bình Thạnh)', wardName: 'Phường 14', district: 'Quận Bình Thạnh', codename: 'phuong_14_quan_binh_thanh', provinceCode: 79 },
      { code: 7917, name: 'Phường 25 (Quận Bình Thạnh)', wardName: 'Phường 25', district: 'Quận Bình Thạnh', codename: 'phuong_25_quan_binh_thanh', provinceCode: 79 },
      { code: 7918, name: 'Phường 2 (Quận Tân Bình)', wardName: 'Phường 2', district: 'Quận Tân Bình', codename: 'phuong_2_quan_tan_binh', provinceCode: 79 },
      { code: 7919, name: 'Phường 12 (Quận Tân Bình)', wardName: 'Phường 12', district: 'Quận Tân Bình', codename: 'phuong_12_quan_tan_binh', provinceCode: 79 },
      { code: 7920, name: 'Phường 15 (Quận Gò Vấp)', wardName: 'Phường 15', district: 'Quận Gò Vấp', codename: 'phuong_15_quan_go_vap', provinceCode: 79 },
      { code: 7921, name: 'Phường 10 (Quận Gò Vấp)', wardName: 'Phường 10', district: 'Quận Gò Vấp', codename: 'phuong_10_quan_go_vap', provinceCode: 79 },
      { code: 7922, name: 'Phường An Phú Đông (Quận 12)', wardName: 'Phường An Phú Đông', district: 'Quận 12', codename: 'phuong_an_phu_dong_quan_12', provinceCode: 79 },
      { code: 7923, name: 'Phường Thạnh Lộc (Quận 12)', wardName: 'Phường Thạnh Lộc', district: 'Quận 12', codename: 'phuong_thanh_loc_quan_12', provinceCode: 79 },
      { code: 7924, name: 'Phường Tân Chánh Hiệp (Quận 12)', wardName: 'Phường Tân Chánh Hiệp', district: 'Quận 12', codename: 'phuong_tan_chanh_hiep_quan_12', provinceCode: 79 },
      { code: 7925, name: 'Phường Hiệp Thành (Quận 12)', wardName: 'Phường Hiệp Thành', district: 'Quận 12', codename: 'phuong_hiep_thanh_quan_12', provinceCode: 79 },
      { code: 7926, name: 'Xã Bình Hưng (Huyện Bình Chánh)', wardName: 'Xã Bình Hưng', district: 'Huyện Bình Chánh', codename: 'xa_binh_hung_huyen_binh_chanh', provinceCode: 79 },
      { code: 7927, name: 'Xã Phong Phú (Huyện Bình Chánh)', wardName: 'Xã Phong Phú', district: 'Huyện Bình Chánh', codename: 'xa_phong_phu_huyen_binh_chanh', provinceCode: 79 },
      { code: 7928, name: 'Thị trấn Hóc Môn (Huyện Hóc Môn)', wardName: 'Thị trấn Hóc Môn', district: 'Huyện Hóc Môn', codename: 'thi_tran_hoc_mon_huyen_hoc_mon', provinceCode: 79 },
    ],
  },
  {
    code: 1,
    name: 'Thành phố Hà Nội',
    codename: 'ha_noi',
    divisionType: 'thành phố trung ương',
    wards: [
      { code: 101, name: 'Phường Tràng Tiền (Quận Hoàn Kiếm)', wardName: 'Phường Tràng Tiền', district: 'Quận Hoàn Kiếm', codename: 'phuong_trang_tien_quan_hoan_kiem', provinceCode: 1 },
      { code: 102, name: 'Phường Hàng Bạc (Quận Hoàn Kiếm)', wardName: 'Phường Hàng Bạc', district: 'Quận Hoàn Kiếm', codename: 'phuong_hang_bac_quan_hoan_kiem', provinceCode: 1 },
      { code: 103, name: 'Phường Hàng Đào (Quận Hoàn Kiếm)', wardName: 'Phường Hàng Đào', district: 'Quận Hoàn Kiếm', codename: 'phuong_hang_dao_quan_hoan_kiem', provinceCode: 1 },
      { code: 104, name: 'Phường Điện Biên (Quận Ba Đình)', wardName: 'Phường Điện Biên', district: 'Quận Ba Đình', codename: 'phuong_dien_bien_quan_ba_dinh', provinceCode: 1 },
      { code: 105, name: 'Phường Kim Mã (Quận Ba Đình)', wardName: 'Phường Kim Mã', district: 'Quận Ba Đình', codename: 'phuong_kim_ma_quan_ba_dinh', provinceCode: 1 },
      { code: 1051, name: 'Phường Cống Vị (Quận Ba Đình)', wardName: 'Phường Cống Vị', district: 'Quận Ba Đình', codename: 'phuong_cong_vi_quan_ba_dinh', provinceCode: 1 },
      { code: 106, name: 'Phường Dịch Vọng (Quận Cầu Giấy)', wardName: 'Phường Dịch Vọng', district: 'Quận Cầu Giấy', codename: 'phuong_dich_vong_quan_cau_giay', provinceCode: 1 },
      { code: 107, name: 'Phường Dịch Vọng Hậu (Quận Cầu Giấy)', wardName: 'Phường Dịch Vọng Hậu', district: 'Quận Cầu Giấy', codename: 'phuong_dich_vong_hau_quan_cau_giay', provinceCode: 1 },
      { code: 108, name: 'Phường Yên Hòa (Quận Cầu Giấy)', wardName: 'Phường Yên Hòa', district: 'Quận Cầu Giấy', codename: 'phuong_yen_hoa_quan_cau_giay', provinceCode: 1 },
      { code: 109, name: 'Phường Mỹ Đình 1 (Quận Nam Từ Liêm)', wardName: 'Phường Mỹ Đình 1', district: 'Quận Nam Từ Liêm', codename: 'phuong_my_dinh_1_quan_nam_tu_liem', provinceCode: 1 },
      { code: 110, name: 'Phường Mỹ Đình 2 (Quận Nam Từ Liêm)', wardName: 'Phường Mỹ Đình 2', district: 'Quận Nam Từ Liêm', codename: 'phuong_my_dinh_2_quan_nam_tu_liem', provinceCode: 1 },
      { code: 111, name: 'Phường Cầu Diễn (Quận Nam Từ Liêm)', wardName: 'Phường Cầu Diễn', district: 'Quận Nam Từ Liêm', codename: 'phuong_cau_dien_quan_nam_tu_liem', provinceCode: 1 },
      { code: 112, name: 'Phường Ô Chợ Dừa (Quận Đống Đa)', wardName: 'Phường Ô Chợ Dừa', district: 'Quận Đống Đa', codename: 'phuong_o_cho_dua_quan_dong_da', provinceCode: 1 },
      { code: 113, name: 'Phường Láng Hạ (Quận Đống Đa)', wardName: 'Phường Láng Hạ', district: 'Quận Đống Đa', codename: 'phuong_lang_ha_quan_dong_da', provinceCode: 1 },
      { code: 114, name: 'Phường Bách Khoa (Quận Hai Bà Trưng)', wardName: 'Phường Bách Khoa', district: 'Quận Hai Bà Trưng', codename: 'phuong_bach_khoa_quan_hai_ba_trung', provinceCode: 1 },
      { code: 115, name: 'Phường Minh Khai (Quận Hai Bà Trưng)', wardName: 'Phường Minh Khai', district: 'Quận Hai Bà Trưng', codename: 'phuong_minh_khai_quan_hai_ba_trung', provinceCode: 1 },
      { code: 116, name: 'Phường Hoàng Liệt (Quận Hoàng Mai)', wardName: 'Phường Hoàng Liệt', district: 'Quận Hoàng Mai', codename: 'phuong_hoang_liet_quan_hoang_mai', provinceCode: 1 },
      { code: 117, name: 'Phường Định Công (Quận Hoàng Mai)', wardName: 'Phường Định Công', district: 'Quận Hoàng Mai', codename: 'phuong_dinh_cong_quan_hoang_mai', provinceCode: 1 },
      { code: 118, name: 'Phường Khương Mai (Quận Thanh Xuân)', wardName: 'Phường Khương Mai', district: 'Quận Thanh Xuân', codename: 'phuong_khuong_mai_quan_thanh_xuan', provinceCode: 1 },
      { code: 119, name: 'Phường Quang Trung (Quận Hà Đông)', wardName: 'Phường Quang Trung', district: 'Quận Hà Đông', codename: 'phuong_quang_trung_quan_ha_dong', provinceCode: 1 },
      { code: 120, name: 'Phường Mộ Lao (Quận Hà Đông)', wardName: 'Phường Mộ Lao', district: 'Quận Hà Đông', codename: 'phuong_mo_lao_quan_ha_dong', provinceCode: 1 },
      { code: 121, name: 'Thị trấn Đông Anh (Huyện Đông Anh)', wardName: 'Thị trấn Đông Anh', district: 'Huyện Đông Anh', codename: 'thi_tran_dong_anh_huyen_dong_anh', provinceCode: 1 },
      { code: 122, name: 'Thị trấn Trâu Quỳ (Huyện Gia Lâm)', wardName: 'Thị trấn Trâu Quỳ', district: 'Huyện Gia Lâm', codename: 'thi_tran_trau_quy_huyen_gia_lam', provinceCode: 1 },
    ],
  },
  {
    code: 48,
    name: 'Thành phố Đà Nẵng',
    codename: 'da_nang',
    divisionType: 'thành phố trung ương',
    wards: [
      { code: 4801, name: 'Phường Hải Châu 1 (Quận Hải Châu)', wardName: 'Phường Hải Châu 1', district: 'Quận Hải Châu', codename: 'phuong_hai_chau_1_quan_hai_chau', provinceCode: 48 },
      { code: 4802, name: 'Phường Thạch Thang (Quận Hải Châu)', wardName: 'Phường Thạch Thang', district: 'Quận Hải Châu', codename: 'phuong_thach_thang_quan_hai_chau', provinceCode: 48 },
      { code: 4803, name: 'Phường Vĩnh Trung (Quận Thanh Khê)', wardName: 'Phường Vĩnh Trung', district: 'Quận Thanh Khê', codename: 'phuong_vinh_trung_quan_thanh_khe', provinceCode: 48 },
      { code: 4804, name: 'Phường An Hải Bắc (Quận Sơn Trà)', wardName: 'Phường An Hải Bắc', district: 'Quận Sơn Trà', codename: 'phuong_an_hai_bac_quan_son_tra', provinceCode: 48 },
      { code: 4805, name: 'Phường Mỹ An (Quận Ngũ Hành Sơn)', wardName: 'Phường Mỹ An', district: 'Quận Ngũ Hành Sơn', codename: 'phuong_my_an_quan_ngu_hanh_son', provinceCode: 48 },
      { code: 4806, name: 'Phường Hòa Khánh Bắc (Quận Liên Chiểu)', wardName: 'Phường Hòa Khánh Bắc', district: 'Quận Liên Chiểu', codename: 'phuong_hoa_khanh_bac_quan_lien_chieu', provinceCode: 48 },
      { code: 4807, name: 'Phường Khuê Trung (Quận Cẩm Lệ)', wardName: 'Phường Khuê Trung', district: 'Quận Cẩm Lệ', codename: 'phuong_khue_trung_quan_cam_le', provinceCode: 48 },
      { code: 4808, name: 'Xã Hòa Châu (Huyện Hòa Vang)', wardName: 'Xã Hòa Châu', district: 'Huyện Hòa Vang', codename: 'xa_hoa_chau_huyen_hoa_vang', provinceCode: 48 },
    ],
  },
  {
    code: 74,
    name: 'Tỉnh Bình Dương',
    codename: 'binh_duong',
    divisionType: 'tỉnh',
    wards: [
      { code: 7401, name: 'Phường Phú Hòa (Thành phố Thủ Dầu Một)', wardName: 'Phường Phú Hòa', district: 'Thành phố Thủ Dầu Một', codename: 'phuong_phu_hoa', provinceCode: 74 },
      { code: 7402, name: 'Phường Hiệp Thành (Thành phố Thủ Dầu Một)', wardName: 'Phường Hiệp Thành', district: 'Thành phố Thủ Dầu Một', codename: 'phuong_hiep_thanh', provinceCode: 74 },
      { code: 7403, name: 'Phường Lái Thiêu (Thành phố Thuận An)', wardName: 'Phường Lái Thiêu', district: 'Thành phố Thuận An', codename: 'phuong_lai_thieu', provinceCode: 74 },
      { code: 7404, name: 'Phường An Phú (Thành phố Thuận An)', wardName: 'Phường An Phú', district: 'Thành phố Thuận An', codename: 'phuong_an_phu', provinceCode: 74 },
      { code: 7405, name: 'Phường Dĩ An (Thành phố Dĩ An)', wardName: 'Phường Dĩ An', district: 'Thành phố Dĩ An', codename: 'phuong_di_an', provinceCode: 74 },
      { code: 7406, name: 'Phường Đông Hòa (Thành phố Dĩ An)', wardName: 'Phường Đông Hòa', district: 'Thành phố Dĩ An', codename: 'phuong_dong_hoa', provinceCode: 74 },
      { code: 7407, name: 'Phường Mỹ Phước (Thị xã Bến Cát)', wardName: 'Phường Mỹ Phước', district: 'Thị xã Bến Cát', codename: 'phuong_my_phuoc', provinceCode: 74 },
      { code: 7408, name: 'Phường Uyên Hưng (Thành phố Tân Uyên)', wardName: 'Phường Uyên Hưng', district: 'Thành phố Tân Uyên', codename: 'phuong_uyen_hung', provinceCode: 74 },
    ],
  },
  {
    code: 75,
    name: 'Tỉnh Đồng Nai',
    codename: 'dong_nai',
    divisionType: 'tỉnh',
    wards: [
      { code: 7501, name: 'Phường Quyết Thắng (Thành phố Biên Hòa)', wardName: 'Phường Quyết Thắng', district: 'Thành phố Biên Hòa', codename: 'phuong_quyet_thang', provinceCode: 75 },
      { code: 7502, name: 'Phường Tân Phong (Thành phố Biên Hòa)', wardName: 'Phường Tân Phong', district: 'Thành phố Biên Hòa', codename: 'phuong_tan_phong', provinceCode: 75 },
      { code: 7503, name: 'Phường Trảng Dài (Thành phố Biên Hòa)', wardName: 'Phường Trảng Dài', district: 'Thành phố Biên Hòa', codename: 'phuong_trang_dai', provinceCode: 75 },
      { code: 7504, name: 'Phường Xuân An (Thành phố Long Khánh)', wardName: 'Phường Xuân An', district: 'Thành phố Long Khánh', codename: 'phuong_xuan_an', provinceCode: 75 },
      { code: 7505, name: 'Thị trấn Long Thành (Huyện Long Thành)', wardName: 'Thị trấn Long Thành', district: 'Huyện Long Thành', codename: 'thi_tran_long_thanh', provinceCode: 75 },
      { code: 7506, name: 'Thị trấn Hiệp Phước (Huyện Nhơn Trạch)', wardName: 'Thị trấn Hiệp Phước', district: 'Huyện Nhơn Trạch', codename: 'thi_tran_hiep_phuoc', provinceCode: 75 },
      { code: 7507, name: 'Thị trấn Trảng Bom (Huyện Trảng Bom)', wardName: 'Thị trấn Trảng Bom', district: 'Huyện Trảng Bom', codename: 'thi_tran_trang_bom', provinceCode: 75 },
    ],
  },
  {
    code: 92,
    name: 'Thành phố Cần Thơ',
    codename: 'can_tho',
    divisionType: 'thành phố trung ương',
    wards: [
      { code: 9201, name: 'Phường Tân An (Quận Ninh Kiều)', wardName: 'Phường Tân An', district: 'Quận Ninh Kiều', codename: 'phuong_tan_an', provinceCode: 92 },
      { code: 9202, name: 'Phường An Khánh (Quận Ninh Kiều)', wardName: 'Phường An Khánh', district: 'Quận Ninh Kiều', codename: 'phuong_an_khanh', provinceCode: 92 },
      { code: 9203, name: 'Phường Bình Thủy (Quận Bình Thủy)', wardName: 'Phường Bình Thủy', district: 'Quận Bình Thủy', codename: 'phuong_binh_thuy', provinceCode: 92 },
      { code: 9204, name: 'Phường Hưng Phú (Quận Cái Răng)', wardName: 'Phường Hưng Phú', district: 'Quận Cái Răng', codename: 'phuong_hung_phu', provinceCode: 92 },
      { code: 9205, name: 'Phường Châu Văn Liêm (Quận Ô Môn)', wardName: 'Phường Châu Văn Liêm', district: 'Quận Ô Môn', codename: 'phuong_chau_van_liem', provinceCode: 92 },
    ],
  },
  {
    code: 31,
    name: 'Thành phố Hải Phòng',
    codename: 'hai_phong',
    divisionType: 'thành phố trung ương',
    wards: [
      { code: 3101, name: 'Phường Hoàng Văn Thụ (Quận Hồng Bàng)', wardName: 'Phường Hoàng Văn Thụ', district: 'Quận Hồng Bàng', codename: 'phuong_hoang_van_thu', provinceCode: 31 },
      { code: 3102, name: 'Phường Lạc Viên (Quận Ngô Quyền)', wardName: 'Phường Lạc Viên', district: 'Quận Ngô Quyền', codename: 'phuong_lac_vien', provinceCode: 31 },
      { code: 3103, name: 'Phường An Dương (Quận Lê Chân)', wardName: 'Phường An Dương', district: 'Quận Lê Chân', codename: 'phuong_an_duong', provinceCode: 31 },
      { code: 3104, name: 'Phường Đằng Hải (Quận Hải An)', wardName: 'Phường Đằng Hải', district: 'Quận Hải An', codename: 'phuong_dang_hai', provinceCode: 31 },
      { code: 3105, name: 'Thị trấn Núi Đèo (Huyện Thủy Nguyên)', wardName: 'Thị trấn Núi Đèo', district: 'Huyện Thủy Nguyên', codename: 'thi_tran_nui_deo', provinceCode: 31 },
    ],
  },
  {
    code: 22,
    name: 'Tỉnh Quảng Ninh',
    codename: 'quang_ninh',
    divisionType: 'tỉnh',
    wards: [
      { code: 2201, name: 'Phường Bạch Đằng (Thành phố Hạ Long)', wardName: 'Phường Bạch Đằng', district: 'Thành phố Hạ Long', codename: 'phuong_bach_dang', provinceCode: 22 },
      { code: 2202, name: 'Phường Bãi Cháy (Thành phố Hạ Long)', wardName: 'Phường Bãi Cháy', district: 'Thành phố Hạ Long', codename: 'phuong_bai_chay', provinceCode: 22 },
      { code: 2203, name: 'Phường Cẩm Thành (Thành phố Cẩm Phả)', wardName: 'Phường Cẩm Thành', district: 'Thành phố Cẩm Phả', codename: 'phuong_cam_thanh', provinceCode: 22 },
      { code: 2204, name: 'Phường Quang Trung (Thành phố Uông Bí)', wardName: 'Phường Quang Trung', district: 'Thành phố Uông Bí', codename: 'phuong_quang_trung', provinceCode: 22 },
      { code: 2205, name: 'Phường Ka Long (Thành phố Móng Cái)', wardName: 'Phường Ka Long', district: 'Thành phố Móng Cái', codename: 'phuong_ka_long', provinceCode: 22 },
    ],
  },
  {
    code: 46,
    name: 'Tỉnh Thừa Thiên Huế',
    codename: 'thua_thien_hue',
    divisionType: 'tỉnh',
    wards: [
      { code: 4601, name: 'Phường Vĩnh Ninh (Thành phố Huế)', wardName: 'Phường Vĩnh Ninh', district: 'Thành phố Huế', codename: 'phuong_vinh_ninh', provinceCode: 46 },
      { code: 4602, name: 'Phường Phú Nhuận (Thành phố Huế)', wardName: 'Phường Phú Nhuận', district: 'Thành phố Huế', codename: 'phuong_phu_nhuan', provinceCode: 46 },
      { code: 4603, name: 'Phường Thuận Lộc (Thành phố Huế)', wardName: 'Phường Thuận Lộc', district: 'Thành phố Huế', codename: 'phuong_thuan_loc', provinceCode: 46 },
      { code: 4604, name: 'Thị trấn Thuận An (Thành phố Huế)', wardName: 'Thị trấn Thuận An', district: 'Thành phố Huế', codename: 'thi_tran_thuan_an', provinceCode: 46 },
    ],
  },
  {
    code: 56,
    name: 'Tỉnh Khánh Hòa',
    codename: 'khanh_hoa',
    divisionType: 'tỉnh',
    wards: [
      { code: 5601, name: 'Phường Lộc Thọ (Thành phố Nha Trang)', wardName: 'Phường Lộc Thọ', district: 'Thành phố Nha Trang', codename: 'phuong_loc_tho', provinceCode: 56 },
      { code: 5602, name: 'Phường Phương Sài (Thành phố Nha Trang)', wardName: 'Phường Phương Sài', district: 'Thành phố Nha Trang', codename: 'phuong_phuong_sai', provinceCode: 56 },
      { code: 5603, name: 'Phường Vĩnh Hải (Thành phố Nha Trang)', wardName: 'Phường Vĩnh Hải', district: 'Thành phố Nha Trang', codename: 'phuong_vinh_hai', provinceCode: 56 },
      { code: 5604, name: 'Phường Cam Phú (Thành phố Cam Ranh)', wardName: 'Phường Cam Phú', district: 'Thành phố Cam Ranh', codename: 'phuong_cam_phu', provinceCode: 56 },
    ],
  },
  {
    code: 40,
    name: 'Tỉnh Nghệ An',
    codename: 'nghe_an',
    divisionType: 'tỉnh',
    wards: [
      { code: 4001, name: 'Phường Quang Trung (Thành phố Vinh)', wardName: 'Phường Quang Trung', district: 'Thành phố Vinh', codename: 'phuong_quang_trung', provinceCode: 40 },
      { code: 4002, name: 'Phường Lê Lợi (Thành phố Vinh)', wardName: 'Phường Lê Lợi', district: 'Thành phố Vinh', codename: 'phuong_le_loi', provinceCode: 40 },
      { code: 4003, name: 'Phường Trường Thi (Thành phố Vinh)', wardName: 'Phường Trường Thi', district: 'Thành phố Vinh', codename: 'phuong_truong_thi', provinceCode: 40 },
      { code: 4004, name: 'Thị xã Cửa Lò', wardName: 'Thị xã Cửa Lò', district: 'Thị xã Cửa Lò', codename: 'thi_xa_cua_lo', provinceCode: 40 },
    ],
  },
  {
    code: 68,
    name: 'Tỉnh Lâm Đồng',
    codename: 'lam_dong',
    divisionType: 'tỉnh',
    wards: [
      { code: 6801, name: 'Phường 1 (Thành phố Đà Lạt)', wardName: 'Phường 1', district: 'Thành phố Đà Lạt', codename: 'phuong_1_da_lat', provinceCode: 68 },
      { code: 6802, name: 'Phường 2 (Thành phố Đà Lạt)', wardName: 'Phường 2', district: 'Thành phố Đà Lạt', codename: 'phuong_2_da_lat', provinceCode: 68 },
      { code: 6803, name: 'Phường 9 (Thành phố Đà Lạt)', wardName: 'Phường 9', district: 'Thành phố Đà Lạt', codename: 'phuong_9_da_lat', provinceCode: 68 },
      { code: 6804, name: 'Phường 1 (Thành phố Bảo Lộc)', wardName: 'Phường 1', district: 'Thành phố Bảo Lộc', codename: 'phuong_1_bao_loc', provinceCode: 68 },
      { code: 6805, name: 'Thị trấn Liên Nghĩa (Huyện Đức Trọng)', wardName: 'Thị trấn Liên Nghĩa', district: 'Huyện Đức Trọng', codename: 'thi_tran_lien_nghia', provinceCode: 68 },
    ],
  },
  {
    code: 4,
    name: 'Tỉnh Cao Bằng',
    codename: 'cao_bang',
    divisionType: 'tỉnh',
    wards: [
      { code: 401, name: 'Phường Hợp Giang (Thành phố Cao Bằng)', wardName: 'Phường Hợp Giang', district: 'Thành phố Cao Bằng', codename: 'phuong_hop_giang', provinceCode: 4 },
      { code: 402, name: 'Phường Sông Bằng (Thành phố Cao Bằng)', wardName: 'Phường Sông Bằng', district: 'Thành phố Cao Bằng', codename: 'phuong_song_bang', provinceCode: 4 },
      { code: 403, name: 'Phường Đề Thám (Thành phố Cao Bằng)', wardName: 'Phường Đề Thám', district: 'Thành phố Cao Bằng', codename: 'phuong_de_tham', provinceCode: 4 },
      { code: 404, name: 'Thị trấn Quảng Uyên (Huyện Quảng Hòa)', wardName: 'Thị trấn Quảng Uyên', district: 'Huyện Quảng Hòa', codename: 'thi_tran_quang_uyen', provinceCode: 4 },
    ],
  },
  {
    code: 24,
    name: 'Tỉnh Bắc Ninh',
    codename: 'bac_ninh',
    divisionType: 'tỉnh',
    wards: [
      { code: 2401, name: 'Phường Tiền An (Thành phố Bắc Ninh)', wardName: 'Phường Tiền An', district: 'Thành phố Bắc Ninh', codename: 'phuong_tien_an', provinceCode: 24 },
      { code: 2402, name: 'Phường Ninh Xá (Thành phố Bắc Ninh)', wardName: 'Phường Ninh Xá', district: 'Thành phố Bắc Ninh', codename: 'phuong_ninh_xa', provinceCode: 24 },
      { code: 2403, name: 'Phường Đông Ngàn (Thành phố Từ Sơn)', wardName: 'Phường Đông Ngàn', district: 'Thành phố Từ Sơn', codename: 'phuong_dong_ngan', provinceCode: 24 },
      { code: 2404, name: 'Thị trấn Chờ (Huyện Yên Phong)', wardName: 'Thị trấn Chờ', district: 'Huyện Yên Phong', codename: 'thi_tran_cho', provinceCode: 24 },
    ],
  },
];
