#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GENERATE MANUAL CLAIM RESOLUTION WORKFLOW (BPMN 2.0 XML & VECTOR SVG)
=====================================================================
Sơ đồ Quy trình Xử lý Sự cố & Khiếu nại Thủ công (As-Is / Manual Fallback SOP)
Chuẩn doanh nghiệp OMG BPMN 2.0 tương thích 100% với Camunda Modeler 5.x và Figma.

Mô tả nghiệp vụ:
- 4 Làn bơi (Lanes):
  1. LÀN 1: KHÁCH HÀNG / MERCHANT (Kênh Liên hệ Thủ công)
  2. LÀN 2: BỘ PHẬN CSKH & TỔNG ĐÀI (Tiếp nhận & Đối chiếu Thủ công)
  3. LÀN 3: BƯU CỤC PHÁT & QUẢN LÝ HUB/KHO (Giám định Thực địa & Biên bản Giấy)
  4. LÀN 4: LÃNH ĐẠO & KẾ TOÁN TÀI CHÍNH (Phê duyệt Tờ trình & Chi tiền Ngân hàng)
- Đặc trưng quy trình thủ công:
  + Toàn bộ là User Task, Manual Task, Send Task (0% AI / 0% DMN tự động).
  + Tra cứu sổ theo dõi / Excel, lục tìm biên bản giấy BBBT trong kho bưu cục.
  + Phê duyệt đa tầng bằng giấy ký tay (Trưởng phòng -> Kế toán trưởng -> Giám đốc).
  + Chi tiền chuyển khoản thủ công từng lệnh qua Internet Banking.
  + Thời gian xử lý: 3 - 5 ngày làm việc (SLA truyền thống).
"""

import os
import html
import xml.etree.ElementTree as ET

def xml_esc(s):
    if s is None:
        return ""
    if not isinstance(s, str):
        s = str(s)
    return html.escape(s, quote=True)

def generate_manual_bpmn_xml():
    xml_lines = []
    xml_lines.append('<?xml version="1.0" encoding="UTF-8"?>')
    xml_lines.append('<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"')
    xml_lines.append('                  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"')
    xml_lines.append('                  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"')
    xml_lines.append('                  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"')
    xml_lines.append('                  xmlns:camunda="http://camunda.org/schema/1.0/bpmn"')
    xml_lines.append('                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"')
    xml_lines.append('                  id="Definitions_Manual_Claim_Process"')
    xml_lines.append('                  targetNamespace="http://bpmn.io/schema/bpmn"')
    xml_lines.append('                  exporter="Camunda Modeler"')
    xml_lines.append('                  exporterVersion="5.48.0">')

    # 1. Collaboration
    xml_lines.append('  <bpmn:collaboration id="Collaboration_Manual_Claim">')
    xml_lines.append('    <bpmn:participant id="Participant_Manual_Logistics"')
    xml_lines.append('                      name="Nexus Logistics (As-Is Manual)"')
    xml_lines.append('                      processRef="Process_Manual_Claim_Resolution" />')
    xml_lines.append('  </bpmn:collaboration>')

    # 2. Process
    xml_lines.append('  <bpmn:process id="Process_Manual_Claim_Resolution" name="Quy Trình Bồi Thường Thủ Công" isExecutable="false">')
    xml_lines.append('    <bpmn:laneSet id="LaneSet_Manual">')

    # Lane 1: Customer
    xml_lines.append('      <bpmn:lane id="Lane_Cust" name="Làn 1: Khách Hàng / Merchant">')
    xml_lines.append('        <bpmn:flowNodeRef>Event_Cust_Start</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_Cust_Submit_Complaint</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_Cust_Send_More_Docs</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Event_Cust_Refund_Received</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Event_Cust_Rejected</bpmn:flowNodeRef>')
    xml_lines.append('      </bpmn:lane>')

    # Lane 2: CSKH
    xml_lines.append('      <bpmn:lane id="Lane_CSKH" name="Làn 2: Bộ Phận CSKH">')
    xml_lines.append('        <bpmn:flowNodeRef>Task_CSKH_Log_Excel</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_CSKH_Check_Docs</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>GW_Docs_Complete</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_CSKH_Calculate_Loss</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_CSKH_Draft_Proposal</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_CSKH_Notify_Result</bpmn:flowNodeRef>')
    xml_lines.append('      </bpmn:lane>')

    # Lane 3: Hub & Operations
    xml_lines.append('      <bpmn:lane id="Lane_Hub" name="Làn 3: Điều Hành Hub &amp; Kho">')
    xml_lines.append('        <bpmn:flowNodeRef>Task_Hub_Search_Paper_BBBT</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_Hub_Interview_Courier</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_Hub_Sign_Physical_Report</bpmn:flowNodeRef>')
    xml_lines.append('      </bpmn:lane>')

    # Lane 4: Management & Finance
    xml_lines.append('      <bpmn:lane id="Lane_Finance" name="Làn 4: Kế Toán &amp; Lãnh Đạo">')
    xml_lines.append('        <bpmn:flowNodeRef>Task_Mgr_Review_Paper</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>GW_Mgr_Decision</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_Acc_Create_Payment_Order</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Task_Acc_Transfer_Manual</bpmn:flowNodeRef>')
    xml_lines.append('        <bpmn:flowNodeRef>Event_Manual_Finished</bpmn:flowNodeRef>')
    xml_lines.append('      </bpmn:lane>')

    xml_lines.append('    </bpmn:laneSet>')

    # Nodes - Lane 1
    xml_lines.append('    <bpmn:startEvent id="Event_Cust_Start" name="Phát hiện sự cố kiện hàng">')
    xml_lines.append('      <bpmn:outgoing>Flow_Cust_1</bpmn:outgoing>')
    xml_lines.append('    </bpmn:startEvent>')
    xml_lines.append('    <bpmn:userTask id="Task_Cust_Submit_Complaint" name="Gọi tổng đài hoặc gửi email khiếu nại (TASK-M1.1)" camunda:candidateGroups="merchants">')
    xml_lines.append('      <bpmn:incoming>Flow_Cust_1</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Cust_to_CSKH</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:userTask id="Task_Cust_Send_More_Docs" name="Bổ sung ảnh chụp &amp; Hóa đơn qua email/Zalo (TASK-M1.2)" camunda:candidateGroups="merchants">')
    xml_lines.append('      <bpmn:incoming>Flow_Docs_Missing</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Cust_Docs_Resubmitted</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:endEvent id="Event_Cust_Refund_Received" name="Nhận tiền bồi thường &amp; Đóng khiếu nại">')
    xml_lines.append('      <bpmn:incoming>Flow_Finish_to_Cust_Success</bpmn:incoming>')
    xml_lines.append('    </bpmn:endEvent>')
    xml_lines.append('    <bpmn:endEvent id="Event_Cust_Rejected" name="Nhận thông báo bác đơn &amp; Đóng khiếu nại">')
    xml_lines.append('      <bpmn:incoming>Flow_Finish_to_Cust_Reject</bpmn:incoming>')
    xml_lines.append('      <bpmn:terminateEventDefinition id="TerminateDef_Cust_Reject" />')
    xml_lines.append('    </bpmn:endEvent>')

    # Nodes - Lane 2
    xml_lines.append('    <bpmn:userTask id="Task_CSKH_Log_Excel" name="Ghi nhận thông tin vào Sổ theo dõi / Excel (TASK-M2.1)" camunda:candidateGroups="cskh_operators">')
    xml_lines.append('      <bpmn:incoming>Flow_Cust_to_CSKH</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_CSKH_1</bpmn:outgoing>')
    xml_lines.append('      <bpmn:dataInputAssociation id="DataAssoc_Excel_Write">')
    xml_lines.append('        <bpmn:sourceRef>DataStore_Excel</bpmn:sourceRef>')
    xml_lines.append('        <bpmn:targetRef>Task_CSKH_Log_Excel</bpmn:targetRef>')
    xml_lines.append('      </bpmn:dataInputAssociation>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:userTask id="Task_CSKH_Check_Docs" name="Kiểm tra tính hợp lệ của biên bản &amp; Ảnh chụp (TASK-M2.2)" camunda:candidateGroups="cskh_operators">')
    xml_lines.append('      <bpmn:incoming>Flow_CSKH_1</bpmn:incoming>')
    xml_lines.append('      <bpmn:incoming>Flow_Cust_Docs_Resubmitted</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_CSKH_to_GW</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:exclusiveGateway id="GW_Docs_Complete" name="Hồ sơ đủ chứng từ?">')
    xml_lines.append('      <bpmn:incoming>Flow_CSKH_to_GW</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Docs_Missing</bpmn:outgoing>')
    xml_lines.append('      <bpmn:outgoing>Flow_Docs_OK</bpmn:outgoing>')
    xml_lines.append('    </bpmn:exclusiveGateway>')
    xml_lines.append('    <bpmn:userTask id="Task_CSKH_Calculate_Loss" name="Tra cứu bảng quy chế &amp; Tính mức bồi hoàn trên Excel (TASK-M2.3)" camunda:candidateGroups="cskh_operators">')
    xml_lines.append('      <bpmn:incoming>Flow_Hub_to_CSKH</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_CSKH_to_Proposal</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:userTask id="Task_CSKH_Draft_Proposal" name="In Tờ trình đề xuất bồi thường ký tay (TASK-M2.4)" camunda:candidateGroups="cskh_operators">')
    xml_lines.append('      <bpmn:incoming>Flow_CSKH_to_Proposal</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Proposal_to_Mgr</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:sendTask id="Task_CSKH_Notify_Result" name="Soạn email &amp; Gọi điện thông báo kết quả cho khách (TASK-M2.5)">')
    xml_lines.append('      <bpmn:incoming>Flow_Mgr_Rejected</bpmn:incoming>')
    xml_lines.append('      <bpmn:incoming>Flow_Acc_Done_to_Notify</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Notify_to_Cust_Branch</bpmn:outgoing>')
    xml_lines.append('    </bpmn:sendTask>')

    # Nodes - Lane 3
    xml_lines.append('    <bpmn:userTask id="Task_Hub_Search_Paper_BBBT" name="Lục tìm Biên bản bất thường (BBBT) lưu tại bưu cục (TASK-M3.1)" camunda:candidateGroups="hub_operators">')
    xml_lines.append('      <bpmn:incoming>Flow_Docs_OK</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Hub_1</bpmn:outgoing>')
    xml_lines.append('      <bpmn:dataInputAssociation id="DataAssoc_Paper_Archive">')
    xml_lines.append('        <bpmn:sourceRef>DataStore_Physical_Archive</bpmn:sourceRef>')
    xml_lines.append('        <bpmn:targetRef>Task_Hub_Search_Paper_BBBT</bpmn:targetRef>')
    xml_lines.append('      </bpmn:dataInputAssociation>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:manualTask id="Task_Hub_Interview_Courier" name="Lấy lời khai bưu tá &amp; Trích xuất camera băng chuyền (TASK-M3.2)">')
    xml_lines.append('      <bpmn:incoming>Flow_Hub_1</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Hub_2</bpmn:outgoing>')
    xml_lines.append('    </bpmn:manualTask>')
    xml_lines.append('    <bpmn:userTask id="Task_Hub_Sign_Physical_Report" name="Lập &amp; Ký Biên bản giám định nguyên nhân tổn thất (TASK-M3.3)" camunda:candidateGroups="hub_operators">')
    xml_lines.append('      <bpmn:incoming>Flow_Hub_2</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Hub_to_CSKH</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')

    # Nodes - Lane 4
    xml_lines.append('    <bpmn:userTask id="Task_Mgr_Review_Paper" name="Trưởng phòng CSKH xem xét Tờ trình &amp; Ký duyệt (TASK-M4.1)" camunda:candidateGroups="managers">')
    xml_lines.append('      <bpmn:incoming>Flow_Proposal_to_Mgr</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Mgr_to_GW</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:exclusiveGateway id="GW_Mgr_Decision" name="Lãnh đạo phê duyệt?">')
    xml_lines.append('      <bpmn:incoming>Flow_Mgr_to_GW</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Mgr_Approved</bpmn:outgoing>')
    xml_lines.append('      <bpmn:outgoing>Flow_Mgr_Rejected</bpmn:outgoing>')
    xml_lines.append('    </bpmn:exclusiveGateway>')
    xml_lines.append('    <bpmn:userTask id="Task_Acc_Create_Payment_Order" name="Kế toán lập Ủy nhiệm chi (UNC) &amp; Trình Giám đốc ký (TASK-M4.2)" camunda:candidateGroups="accountants">')
    xml_lines.append('      <bpmn:incoming>Flow_Mgr_Approved</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Acc_to_Transfer</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:userTask id="Task_Acc_Transfer_Manual" name="Thực hiện chuyển khoản thủ công qua e-Banking (TASK-M4.3)" camunda:candidateGroups="accountants">')
    xml_lines.append('      <bpmn:incoming>Flow_Acc_to_Transfer</bpmn:incoming>')
    xml_lines.append('      <bpmn:outgoing>Flow_Acc_Done_to_End</bpmn:outgoing>')
    xml_lines.append('      <bpmn:outgoing>Flow_Acc_Done_to_Notify</bpmn:outgoing>')
    xml_lines.append('    </bpmn:userTask>')
    xml_lines.append('    <bpmn:endEvent id="Event_Manual_Finished" name="Đóng hồ sơ &amp; Lưu trữ chứng từ kế toán">')
    xml_lines.append('      <bpmn:incoming>Flow_Acc_Done_to_End</bpmn:incoming>')
    xml_lines.append('    </bpmn:endEvent>')

    # Sequence Flows
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Cust_1" sourceRef="Event_Cust_Start" targetRef="Task_Cust_Submit_Complaint" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Cust_to_CSKH" sourceRef="Task_Cust_Submit_Complaint" targetRef="Task_CSKH_Log_Excel" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_CSKH_1" sourceRef="Task_CSKH_Log_Excel" targetRef="Task_CSKH_Check_Docs" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_CSKH_to_GW" sourceRef="Task_CSKH_Check_Docs" targetRef="GW_Docs_Complete" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Docs_Missing" name="Thiếu hồ sơ / Cần bổ sung" sourceRef="GW_Docs_Complete" targetRef="Task_Cust_Send_More_Docs" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Cust_Docs_Resubmitted" sourceRef="Task_Cust_Send_More_Docs" targetRef="Task_CSKH_Check_Docs" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Docs_OK" name="Hồ sơ hợp lệ" sourceRef="GW_Docs_Complete" targetRef="Task_Hub_Search_Paper_BBBT" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Hub_1" sourceRef="Task_Hub_Search_Paper_BBBT" targetRef="Task_Hub_Interview_Courier" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Hub_2" sourceRef="Task_Hub_Interview_Courier" targetRef="Task_Hub_Sign_Physical_Report" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Hub_to_CSKH" name="Biên bản giấy xác nhận" sourceRef="Task_Hub_Sign_Physical_Report" targetRef="Task_CSKH_Calculate_Loss" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_CSKH_to_Proposal" sourceRef="Task_CSKH_Calculate_Loss" targetRef="Task_CSKH_Draft_Proposal" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Proposal_to_Mgr" name="Trình ký giấy" sourceRef="Task_CSKH_Draft_Proposal" targetRef="Task_Mgr_Review_Paper" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Mgr_to_GW" sourceRef="Task_Mgr_Review_Paper" targetRef="GW_Mgr_Decision" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Mgr_Approved" name="Duyệt chi" sourceRef="GW_Mgr_Decision" targetRef="Task_Acc_Create_Payment_Order" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Mgr_Rejected" name="Bác bỏ đề xuất" sourceRef="GW_Mgr_Decision" targetRef="Task_CSKH_Notify_Result" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Acc_to_Transfer" sourceRef="Task_Acc_Create_Payment_Order" targetRef="Task_Acc_Transfer_Manual" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Acc_Done_to_End" sourceRef="Task_Acc_Transfer_Manual" targetRef="Event_Manual_Finished" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Acc_Done_to_Notify" sourceRef="Task_Acc_Transfer_Manual" targetRef="Task_CSKH_Notify_Result" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Notify_to_Cust_Branch" sourceRef="Task_CSKH_Notify_Result" targetRef="Event_Cust_Refund_Received" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Finish_to_Cust_Success" sourceRef="Task_CSKH_Notify_Result" targetRef="Event_Cust_Refund_Received" />')
    xml_lines.append('    <bpmn:sequenceFlow id="Flow_Finish_to_Cust_Reject" sourceRef="Task_CSKH_Notify_Result" targetRef="Event_Cust_Rejected" />')

    # Data Stores
    xml_lines.append('    <bpmn:dataStoreReference id="DataStore_Excel" name="Sổ theo dõi &amp; File Excel [DOC-01]" />')
    xml_lines.append('    <bpmn:dataStoreReference id="DataStore_Physical_Archive" name="Kho Biên bản giấy BBBT [DOC-02]" />')

    # Text Annotations
    xml_lines.append('    <bpmn:textAnnotation id="Annotation_Manual_SLA">')
    xml_lines.append('      <bpmn:text>SLA Xử lý truyền thống: 3 - 5 ngày làm việc&#10;Hạn chế: Dễ thất lạc hồ sơ, phụ thuộc nhân sự</bpmn:text>')
    xml_lines.append('    </bpmn:textAnnotation>')
    xml_lines.append('    <bpmn:association id="Assoc_Manual_SLA" sourceRef="Task_CSKH_Draft_Proposal" targetRef="Annotation_Manual_SLA" />')

    xml_lines.append('  </bpmn:process>')

    # 3. Diagram Interchange (BPMNDI)
    xml_lines.append('  <bpmndi:BPMNDiagram id="BPMNDiagram_Manual">')
    xml_lines.append('    <bpmndi:BPMNPlane id="BPMNPlane_Manual" bpmnElement="Collaboration_Manual_Claim">')

    # Participant
    xml_lines.append('      <bpmndi:BPMNShape id="Participant_Manual_di" bpmnElement="Participant_Manual_Logistics" isHorizontal="true">')
    xml_lines.append('        <dc:Bounds x="160" y="80" width="1980" height="920" />')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Lanes
    xml_lines.append('      <bpmndi:BPMNShape id="Lane_Cust_di" bpmnElement="Lane_Cust" isHorizontal="true">')
    xml_lines.append('        <dc:Bounds x="190" y="80" width="1950" height="230" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Lane_CSKH_di" bpmnElement="Lane_CSKH" isHorizontal="true">')
    xml_lines.append('        <dc:Bounds x="190" y="310" width="1950" height="230" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Lane_Hub_di" bpmnElement="Lane_Hub" isHorizontal="true">')
    xml_lines.append('        <dc:Bounds x="190" y="540" width="1950" height="230" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Lane_Finance_di" bpmnElement="Lane_Finance" isHorizontal="true">')
    xml_lines.append('        <dc:Bounds x="190" y="770" width="1950" height="230" />')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Lane 1 Shapes
    xml_lines.append('      <bpmndi:BPMNShape id="Event_Cust_Start_di" bpmnElement="Event_Cust_Start">')
    xml_lines.append('        <dc:Bounds x="232" y="177" width="36" height="36" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="212" y="220" width="78" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_Cust_Submit_Complaint_di" bpmnElement="Task_Cust_Submit_Complaint">')
    xml_lines.append('        <dc:Bounds x="320" y="155" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_Cust_Send_More_Docs_di" bpmnElement="Task_Cust_Send_More_Docs">')
    xml_lines.append('        <dc:Bounds x="780" y="155" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Event_Cust_Refund_Received_di" bpmnElement="Event_Cust_Refund_Received">')
    xml_lines.append('        <dc:Bounds x="2012" y="177" width="36" height="36" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1985" y="220" width="90" height="40" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Event_Cust_Rejected_di" bpmnElement="Event_Cust_Rejected">')
    xml_lines.append('        <dc:Bounds x="2012" y="247" width="36" height="36" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1985" y="290" width="90" height="40" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Lane 2 Shapes
    xml_lines.append('      <bpmndi:BPMNShape id="Task_CSKH_Log_Excel_di" bpmnElement="Task_CSKH_Log_Excel">')
    xml_lines.append('        <dc:Bounds x="320" y="385" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_CSKH_Check_Docs_di" bpmnElement="Task_CSKH_Check_Docs">')
    xml_lines.append('        <dc:Bounds x="500" y="385" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="GW_Docs_Complete_di" bpmnElement="GW_Docs_Complete" isMarkerVisible="true">')
    xml_lines.append('        <dc:Bounds x="695" y="400" width="50" height="50" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="680" y="370" width="80" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_CSKH_Calculate_Loss_di" bpmnElement="Task_CSKH_Calculate_Loss">')
    xml_lines.append('        <dc:Bounds x="1220" y="385" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_CSKH_Draft_Proposal_di" bpmnElement="Task_CSKH_Draft_Proposal">')
    xml_lines.append('        <dc:Bounds x="1410" y="385" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_CSKH_Notify_Result_di" bpmnElement="Task_CSKH_Notify_Result">')
    xml_lines.append('        <dc:Bounds x="1820" y="385" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Data Store 1
    xml_lines.append('      <bpmndi:BPMNShape id="DataStore_Excel_di" bpmnElement="DataStore_Excel">')
    xml_lines.append('        <dc:Bounds x="365" y="485" width="50" height="50" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="350" y="542" width="80" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Lane 3 Shapes
    xml_lines.append('      <bpmndi:BPMNShape id="Task_Hub_Search_Paper_BBBT_di" bpmnElement="Task_Hub_Search_Paper_BBBT">')
    xml_lines.append('        <dc:Bounds x="650" y="615" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_Hub_Interview_Courier_di" bpmnElement="Task_Hub_Interview_Courier">')
    xml_lines.append('        <dc:Bounds x="840" y="615" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_Hub_Sign_Physical_Report_di" bpmnElement="Task_Hub_Sign_Physical_Report">')
    xml_lines.append('        <dc:Bounds x="1030" y="615" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Data Store 2
    xml_lines.append('      <bpmndi:BPMNShape id="DataStore_Physical_Archive_di" bpmnElement="DataStore_Physical_Archive">')
    xml_lines.append('        <dc:Bounds x="695" y="705" width="50" height="50" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="680" y="762" width="80" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Lane 4 Shapes
    xml_lines.append('      <bpmndi:BPMNShape id="Task_Mgr_Review_Paper_di" bpmnElement="Task_Mgr_Review_Paper">')
    xml_lines.append('        <dc:Bounds x="1410" y="845" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="GW_Mgr_Decision_di" bpmnElement="GW_Mgr_Decision" isMarkerVisible="true">')
    xml_lines.append('        <dc:Bounds x="1605" y="860" width="50" height="50" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1595" y="917" width="70" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_Acc_Create_Payment_Order_di" bpmnElement="Task_Acc_Create_Payment_Order">')
    xml_lines.append('        <dc:Bounds x="1710" y="845" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Task_Acc_Transfer_Manual_di" bpmnElement="Task_Acc_Transfer_Manual">')
    xml_lines.append('        <dc:Bounds x="1890" y="845" width="140" height="80" />')
    xml_lines.append('      </bpmndi:BPMNShape>')
    xml_lines.append('      <bpmndi:BPMNShape id="Event_Manual_Finished_di" bpmnElement="Event_Manual_Finished">')
    xml_lines.append('        <dc:Bounds x="2082" y="867" width="36" height="36" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="2060" y="910" width="80" height="40" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Annotation Shape
    xml_lines.append('      <bpmndi:BPMNShape id="Annotation_Manual_SLA_di" bpmnElement="Annotation_Manual_SLA">')
    xml_lines.append('        <dc:Bounds x="1400" y="325" width="220" height="45" />')
    xml_lines.append('      </bpmndi:BPMNShape>')

    # Edges
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Cust_1_di" bpmnElement="Flow_Cust_1">')
    xml_lines.append('        <di:waypoint x="268" y="195" />')
    xml_lines.append('        <di:waypoint x="320" y="195" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Cust_to_CSKH_di" bpmnElement="Flow_Cust_to_CSKH">')
    xml_lines.append('        <di:waypoint x="390" y="235" />')
    xml_lines.append('        <di:waypoint x="390" y="385" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_CSKH_1_di" bpmnElement="Flow_CSKH_1">')
    xml_lines.append('        <di:waypoint x="460" y="425" />')
    xml_lines.append('        <di:waypoint x="500" y="425" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_CSKH_to_GW_di" bpmnElement="Flow_CSKH_to_GW">')
    xml_lines.append('        <di:waypoint x="640" y="425" />')
    xml_lines.append('        <di:waypoint x="695" y="425" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Docs_Missing_di" bpmnElement="Flow_Docs_Missing">')
    xml_lines.append('        <di:waypoint x="720" y="400" />')
    xml_lines.append('        <di:waypoint x="720" y="195" />')
    xml_lines.append('        <di:waypoint x="780" y="195" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="640" y="270" width="75" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Cust_Docs_Resubmitted_di" bpmnElement="Flow_Cust_Docs_Resubmitted">')
    xml_lines.append('        <di:waypoint x="850" y="235" />')
    xml_lines.append('        <di:waypoint x="850" y="360" />')
    xml_lines.append('        <di:waypoint x="570" y="360" />')
    xml_lines.append('        <di:waypoint x="570" y="385" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Docs_OK_di" bpmnElement="Flow_Docs_OK">')
    xml_lines.append('        <di:waypoint x="720" y="450" />')
    xml_lines.append('        <di:waypoint x="720" y="615" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="730" y="520" width="65" height="14" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Hub_1_di" bpmnElement="Flow_Hub_1">')
    xml_lines.append('        <di:waypoint x="790" y="655" />')
    xml_lines.append('        <di:waypoint x="840" y="655" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Hub_2_di" bpmnElement="Flow_Hub_2">')
    xml_lines.append('        <di:waypoint x="980" y="655" />')
    xml_lines.append('        <di:waypoint x="1030" y="655" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Hub_to_CSKH_di" bpmnElement="Flow_Hub_to_CSKH">')
    xml_lines.append('        <di:waypoint x="1170" y="655" />')
    xml_lines.append('        <di:waypoint x="1290" y="655" />')
    xml_lines.append('        <di:waypoint x="1290" y="465" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1200" y="580" width="80" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_CSKH_to_Proposal_di" bpmnElement="Flow_CSKH_to_Proposal">')
    xml_lines.append('        <di:waypoint x="1360" y="425" />')
    xml_lines.append('        <di:waypoint x="1410" y="425" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Proposal_to_Mgr_di" bpmnElement="Flow_Proposal_to_Mgr">')
    xml_lines.append('        <di:waypoint x="1480" y="465" />')
    xml_lines.append('        <di:waypoint x="1480" y="845" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1490" y="650" width="65" height="14" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Mgr_to_GW_di" bpmnElement="Flow_Mgr_to_GW">')
    xml_lines.append('        <di:waypoint x="1550" y="885" />')
    xml_lines.append('        <di:waypoint x="1605" y="885" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Mgr_Approved_di" bpmnElement="Flow_Mgr_Approved">')
    xml_lines.append('        <di:waypoint x="1655" y="885" />')
    xml_lines.append('        <di:waypoint x="1710" y="885" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1655" y="865" width="48" height="14" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Mgr_Rejected_di" bpmnElement="Flow_Mgr_Rejected">')
    xml_lines.append('        <di:waypoint x="1630" y="860" />')
    xml_lines.append('        <di:waypoint x="1630" y="520" />')
    xml_lines.append('        <di:waypoint x="1850" y="520" />')
    xml_lines.append('        <di:waypoint x="1850" y="465" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1660" y="500" width="75" height="14" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Acc_to_Transfer_di" bpmnElement="Flow_Acc_to_Transfer">')
    xml_lines.append('        <di:waypoint x="1850" y="885" />')
    xml_lines.append('        <di:waypoint x="1890" y="885" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Acc_Done_to_End_di" bpmnElement="Flow_Acc_Done_to_End">')
    xml_lines.append('        <di:waypoint x="2030" y="885" />')
    xml_lines.append('        <di:waypoint x="2082" y="885" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Acc_Done_to_Notify_di" bpmnElement="Flow_Acc_Done_to_Notify">')
    xml_lines.append('        <di:waypoint x="1960" y="845" />')
    xml_lines.append('        <di:waypoint x="1960" y="650" />')
    xml_lines.append('        <di:waypoint x="1890" y="650" />')
    xml_lines.append('        <di:waypoint x="1890" y="465" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Finish_to_Cust_Success_di" bpmnElement="Flow_Finish_to_Cust_Success">')
    xml_lines.append('        <di:waypoint x="1920" y="385" />')
    xml_lines.append('        <di:waypoint x="1920" y="195" />')
    xml_lines.append('        <di:waypoint x="2012" y="195" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1925" y="270" width="70" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Flow_Finish_to_Cust_Reject_di" bpmnElement="Flow_Finish_to_Cust_Reject">')
    xml_lines.append('        <di:waypoint x="1940" y="385" />')
    xml_lines.append('        <di:waypoint x="1940" y="265" />')
    xml_lines.append('        <di:waypoint x="2012" y="265" />')
    xml_lines.append('        <bpmndi:BPMNLabel><dc:Bounds x="1945" y="310" width="60" height="27" /></bpmndi:BPMNLabel>')
    xml_lines.append('      </bpmndi:BPMNEdge>')

    # Data Associations
    xml_lines.append('      <bpmndi:BPMNEdge id="DataAssoc_Excel_Write_di" bpmnElement="DataAssoc_Excel_Write">')
    xml_lines.append('        <di:waypoint x="390" y="485" />')
    xml_lines.append('        <di:waypoint x="390" y="465" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="DataAssoc_Paper_Archive_di" bpmnElement="DataAssoc_Paper_Archive">')
    xml_lines.append('        <di:waypoint x="720" y="705" />')
    xml_lines.append('        <di:waypoint x="720" y="695" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')
    xml_lines.append('      <bpmndi:BPMNEdge id="Assoc_Manual_SLA_di" bpmnElement="Assoc_Manual_SLA">')
    xml_lines.append('        <di:waypoint x="1480" y="385" />')
    xml_lines.append('        <di:waypoint x="1480" y="370" />')
    xml_lines.append('      </bpmndi:BPMNEdge>')

    xml_lines.append('    </bpmndi:BPMNPlane>')
    xml_lines.append('  </bpmndi:BPMNDiagram>')
    xml_lines.append('</bpmn:definitions>')

    return "\n".join(xml_lines)

def main():
    target_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../docs/graduation-thesis/figma-page-2-process-and-ai-pipeline/diagrams"))
    os.makedirs(target_dir, exist_ok=True)
    target_bpmn = os.path.join(target_dir, "00-bpmn-manual-claim-resolution.bpmn")

    print(f"Generating Manual Claim BPMN 2.0 XML to:\n  {target_bpmn}")
    bpmn_content = generate_manual_bpmn_xml()

    # XML Validation
    try:
        ET.fromstring(bpmn_content)
        print(">> Strict XML Validation Passed: Valid BPMN 2.0 XML.")
    except Exception as e:
        print(f"!! XML Validation Failed: {e}")
        raise

    with open(target_bpmn, "w", encoding="utf-8") as f:
        f.write(bpmn_content)

    print(f">> Successfully generated Camunda BPMN 2.0 file: {os.path.getsize(target_bpmn)} bytes.")

if __name__ == "__main__":
    main()
